service: chatbot-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3

functions:
  chatbotInteraction:
    handler: handler.chatbotInteraction
    events:
      - http:
          path: chatbot
          method: post

