service: chatbot-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2 # Ensure this matches your Lambda function and DynamoDB table's region
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lex:PostText"
        - "lex:RecognizeText" # Ensure Lambda can call Lex's RecognizeText API
        - "dynamodb:Query" # Permission for DynamoDB Query action
        - "dynamodb:GetItem" # Optional, add if your logic requires getting specific items
      Resource: "*" # For finer control in production, specify actual ARN(s) for Lex and DynamoDB resources

functions:
  chatbotInteraction:
    handler: handler.chatbotInteraction
    events:
      - http:
          path: chatbot
          method: post

