service: posts-service

frameworkVersion: '3'

plugins:
  - serverless-package-external

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  environment:
    POSTS_TABLE: postsTable
    ANALYTICS_TABLE: analyticsTable  # Reference the existing analyticsTable
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:DeleteItem"
          Resource: "arn:aws:dynamodb:eu-west-3:637423166046:table/postsTable"
        - Effect: "Allow"
          Action:
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:DeleteItem"
          Resource: "arn:aws:dynamodb:eu-west-3:637423166046:table/analyticsTable"  # Reference the existing analyticsTable
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
          Resource: "arn:aws:s3:::analytics-service-dev-serverlessdeploymentbucket-iky5wevabpyu/AnalyticsService/handler.js"

functions:
  createPost:
    handler: handler.createPost
    events:
      - http:
          path: posts
          method: post
    package:
      include:
        - ../AnalyticsService/**   # Include the AnalyticsService directory and its contents
      exclude:
        - node_modules/**          # Exclude node_modules directory and its contents

  deletePost:
    handler: handler.deletePost
    events:
      - http:
          path: posts/{postId}
          method: delete
    package:
      include:
        - ../AnalyticsService/**   # Include the AnalyticsService directory and its contents
      exclude:
        - node_modules/**          # Exclude node_modules directory and its contents

resources:
  Resources:
    postsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.POSTS_TABLE}
        AttributeDefinitions:
          - AttributeName: "postId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "postId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

