service: analytics-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  environment:
    ANALYTICS_TABLE: analyticsTable
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: 
        - "arn:aws:dynamodb:${self:provider.region}:637423166046:table/${self:provider.environment.ANALYTICS_TABLE}"

functions:
  fetchAnalytics:
    handler: handler.fetchAnalytics
    events:
      - http:
          path: analytics/{userId}
          method: get

resources:
  Resources:
    AnalyticsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ANALYTICS_TABLE}
        AttributeDefinitions:
          - AttributeName: "userId"
            AttributeType: "S"
          - AttributeName: "date"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "userId"
            KeyType: "HASH"
          - AttributeName: "date"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: DateIndex
            KeySchema:
              - AttributeName: "date"
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"

