service: user-profile-service

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3  # Specify your AWS region
  environment:
    USER_PROFILES_TABLE: usersTable  # Assuming 'usersTable' is your DynamoDB table for user profiles
    S3_BUCKET_NAME: profile-pictures-social  # Updated with your actual S3 bucket name
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_PROFILES_TABLE}"
    - Effect: "Allow"
      Action: "s3:PutObject"
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}/profile-pictures/*"

functions:
  updateUserProfile:
    handler: handler.updateUserProfile
    events:
      - http:
          path: user/profile
          method: post

